#!/bin/bash
#-------------------------------------------------------------
# Filter a CGI file lines for genotype call rate >= threshold.
#
# Usage: filter-cgi-genotypes <cgi-file> <call-rate-threshold>
#-------------------------------------------------------------
num_samples=`zcat $1 | head -1 | awk '{print NF-8}'`
a=`echo "${2} * ${num_samples}" | bc`
threshold=`python -c "from math import ceil; print int(ceil(${a}))"`

# Print first column, which is a unique identifier of the row
zcat $1 | sed '1d' | awk "BEGIN { FS=\"\t\";} \
     { s=0; \
     for (i = 1; i <= NF; i++) { \
     	 if ((\$i==\"00\") || (\$i==\"01\") || (\$i ==\"11\")) { \
	    s++; \
         } \
     } \
     if (s >= ${threshold}) { print \$1; } \
}"
