#!/bin/bash
#-----------------------------------------------------------------
# Count genotypes in an imputed CGI file of a each chromosome.
#-----------------------------------------------------------------
#PBS -l walltime=00:30:00
#PBS -l mppwidth=528
#PBS -N trim_cgi
#PBS -q batch
#PBS -A CI-MCB000155
#PBS -j oe

echo /opt/modules/default
. /opt/modules/default/init/bash
module swap PrgEnv-pgi PrgEnv-gnu
module load python/2.7.3-vanilla
module list 2>&1
cd $PBS_O_WORKDIR

for c in `seq 1 22`; do
    aprun -n 1 -N 1 -d 1 /lustre/beagle/ober/users/oren/ober/code/impute/batch/cgi/trim_cgi.sh $c &
done
wait
