#!/bin/bash
#--------------------------------------------------------------------
# IMPUTE2 post-processing after pedigree-based imputation.
#
# Author: Oren E. Livne
# Date:   08-OCT-2013
#--------------------------------------------------------------------

if [[ $# -ne 4 ]]; then
    echo -e "Usage: `basename $0` <work-dir> <imputed-dir> <chrom> <out-dir>"
    exit ${E_BADARGS}
fi
work_dir="$1"
imputed_dir="$2"
chrom="$3"
out_dir="$4"

# Constants
suffix="haps"
work_in_prefix="run_impute2"                 # IMPUTE2 run file prefix
imputed_tfam="${OBER}/testdata/pedigree/hutterites.imputed.tfam"

in_prefix="${imputed_dir}/imputed_cgi"
count_dir="${OBER_OUT}/impute_cgi/count2-po"
out_prefix="${out_dir}/imputed_cgi"
work_chr="${work_dir}/chr${chrom}/${work_in_prefix}"
temp_dir="${work_chr}/temp-po"
work_out_prefix="${work_chr}/impute2.chr${chrom}" # IMPUTE2 Output file prefix
plink_file="${work_out_prefix}.impute2.po" # Final IMPUTE2 PLINK file name

# Initialize, clean
#mkdir -p ${out_dir}
#rm -f ${out_prefix}.chr${chrom}*

#----------------------------------------------------------------
# Merge impute2 output chunks and stats into a single PLINK set
#----------------------------------------------------------------
t="impute2.po.tped"
cat `ls -1 ${work_chr}/node-*/${work_in_prefix}*.${t} | sort | paste -sd' '` > ${work_out_prefix}.${t}
rm -f ${plink_file}.tfam
ln -s ${imputed_tfam} ${plink_file}.tfam

#----------------------------------------------------------------
# Override imputed genotypes with impute2 genotypes
#----------------------------------------------------------------
bash -x ${OBER_CODE}/impute/batch/cgi/override-imputed-by-plink.sh ${in_prefix} ${out_dir} ${plink_file} ${chrom} ${temp_dir} "-k name -n 0 -t 4 -w"

#----------------------------------------------------------------
# Run genotype counting (call rates)
#----------------------------------------------------------------
rm -rf ${count_dir}/chr${chrom}
${OBER_CODE}/impute/batch/cgi/count-genotypes-all ${chrom} ${chrom} "${out_prefix}" "${count_dir}"
