#!/bin/bash
# Run a single window size (#windows = w), chromosome 22, phased/unphased run

w="$1"      # Total number of windows in the run
flags="$2"  # Phased = "-p", unphased = ""
suffix="$3" # Output directory name suffix

out_dir="${OBER_OUT}/impute_cgi/impute2.windows_${w}_$suffix"
pipeline-impute2 -c -g ${flags} -s 22 -e 22 ${out_dir}

# Link big files from existing window directory (impute2.windows_72) to avoid extra time and duplicate storage
cd ${out_dir}/chr22/run_impute2
file_dir="${OBER_OUT}/impute_cgi/impute2.windows_72/chr22/run_impute2"
for f in `find ${file_dir} -maxdepth 1| sed '1d' | egrep -v node-`; do 
    ln -s $f
done

pipeline-impute2 -r ${flags} -s 22 -e 22 ${out_dir}
