####################
##
## Test Condor command file
##
####################

universe	= vanilla
executable	= merge_file
output		= /home/oren/ober/system/condor/examples/dag/out/merge_file.out
error		= /home/oren/ober/system/condor/examples/dag/out/merge_file.err
log		= /home/oren/ober/system/condor/examples/dag/out/merge_file.log
arguments	= output 2 output.txt
should_transfer_files   = YES
transfer_input_files    = output0,output1
when_to_transfer_output = ON_EXIT
Initialdir      = /home/oren/ober/system/condor/examples/dag
notification    = Never
queue
