####################
##
## Test Condor command file
##
####################

universe	= vanilla
executable	= split_file
output		= /home/oren/ober/system/condor/examples/dag/out/split_file.out
error		= /home/oren/ober/system/condor/examples/dag/out/split_file.err
log		= /home/oren/ober/system/condor/examples/dag/out/split_file.log
arguments	= input.txt 2
should_transfer_files   = YES
transfer_input_files    = input.txt
when_to_transfer_output = ON_EXIT
Initialdir      = /home/oren/ober/system/condor/examples/dag
notification    = Never
queue
