#!/bin/bash
#----------------------------------------------------------------
# Find IBD segments of all samples in a sample index range [a,b)
# in segment stdin data.
# 
# Author: Oren E. Livne
# Date:   08-FEB-2013
#----------------------------------------------------------------

# Read input arguments
DARGS=65
PROGNAME=`basename $0`

if [ $# -ne 2 ]; then
  echo "Usage: ${PROGNAME} a b"
  echo ""
  echo "Find IBD segments of all samples in the sample index range [a,b)"
  echo "in segment stdin data."
  exit $E_BADARGS
fi
awk -v i=$1 -v j=$2 '(i <= $5) && ($5 < j) && (i <= $7) && ($7 < j)'
