#!/bin/bash
#---------------------------------------------------------------
# hera web server manager on oberlab-dev.
#
# Version:	hera 2012-08-21 livne@uchicago.edu
#---------------------------------------------------------------

### BEGIN INIT INFO
# Provides:         hera
# Required-Start:    
# Required-Stop:     
# Default-Start:    2 3 4 5
# Default-Stop:     0 1 6
### END INIT INFO

FIRST=no

MONITORS="$2"
USER="$3"
GROUP="$4"
FORMAT="%w/%f"
EVENTS="moved_to,create"
FLAGS=" -m -q -r"
PIDFILE="/var/run/hera.pid"

HOST="10.135.144.36"
PORT="8000"
progname=`basename $0`

hera_server()
{
    [ ! -x $CMD ] && return 1
    [ ! -r /etc/default/rcS ] || . /etc/default/rcS

    . /lib/lsb/init-functions

    case "$1" in
	start)
            echo -ne "Starting hera on $HOST:$PORT:"
	    source /home/oren/.bash_profile
	    cd /home/oren/virtualenvs/ober
	    source bin/activate
	    cd /opt/ober/hera
	    ./manage.py runserver $HOST:$PORT &>/opt/log/hera.log &
            sleep 1
	    ( ps aux | grep python | grep "./manage.py runserver $HOST:$PORT" | awk {'print $2'} | tr "\\n" " " ) > $PIDFILE
	    echo -ne "\t[ Started ]\n"
            return 0
	    ;;
	stop)
        if [ -f $PIDFILE ]
        then
            echo -ne "Stopping hera:"
            kill -9 $(cat $PIDFILE )  > /dev/null 2>&1
            rm $PIDFILE > /dev/null 2>&1
	    echo -ne "\t[ Stopped ]\n"
            return 0
        else
            echo "No PID file found at $PIDFILE. Try $progname forcestop"
        fi
        ;;
    forcestop)
        echo -ne "Killing all hera:"
	( ps aux | grep python | grep "./manage.py runserver $HOST:$PORT" | awk {'print $2'} | xargs -iddd kill -9 ddd ) > /dev/null 2>&1
        rm $PIDFILE > /dev/null 2>&1
	echo -ne "\t[ Killed ]\n"
        return 0
	    ;;
	*)
	    echo "Usage: $progname {start|stop|forcestop}"
	    return 1
	    ;;
    esac
}

hera_server "$@"
