'''
============================================================
A pedigree loaded from an input file from a previous study
at the Ober Lab. Provided by Jessica and Gaixin. Includes
node annotations (generated by Mark) - old_generation #.   

Here 'old' refers to 'from the study'.

Created on May 30, 2012
@author: Oren Livne <livne@uchicago.edu>
============================================================
'''
import numpy as np
from impute.data.Pedigree import Pedigree
from impute.data import io_pedigree

class PedigreeOldStudy(Pedigree):
    def __init__(self, pedigree, old_generation):
        '''Constructor'''
        super(PedigreeOldStudy, self).__init__(pedigree.graph, 
                                               sample_id=pedigree.sample_id, 
                                               sex=pedigree.sex,
                                               phenotype=pedigree.phenotype,
                                               node_type=pedigree.node_type,
                                               sample_index=pedigree.sample_index,
                                               num_genotyped=pedigree.num_genotyped)
        # Generation number of each node provided by the input file from the study
        self.old_generation = old_generation

class PedigreeOldStudyReader(object):
    #---------------------------------------------
    # Methods
    #---------------------------------------------
    def read(self, file_name, genotyped_id_file=None):
        '''Load pedigree from file in old format.'''

        p = io_pedigree.read(file_name, genotyped_id_file)
        # Load data from text file a second time to read the old-study-specific-column. Not efficient.
        data = np.genfromtxt(file_name, np.dtype(int))
        old_generation = dict(data[:,(1,6)])
        
        # Wrap by old pedigree object 
        return PedigreeOldStudy(p, old_generation)
        